import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-bottons";
import { HomeIcon } from "lucide-react";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
subsets: ["latin"],
weight: ["100", "200", "300","400","500","600","700","800","900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins} antialiased`}
      >
        <AuthProvider>
        <nav className="flex  bg-black text-white p-4 items-center justify-between">
          <Link 
            href="/" 
            className="text-3xl tracking-widest flex items-center gap-2 uppercase">
          <HomeIcon />
          <span>Properties</span>
          </Link>
          <ul className="flex gap-6 items-center">
            <li>
              <Link href="profile" className="hover:upderline">
                Search
              </Link>
            </li>
            <li><AuthButtons/></li>
          </ul>
        </nav>
        {children}
        <Toaster richColors closeButton />
        </AuthProvider>
      </body>
    </html>
  );
}
